name: Exercice Complet
on: workflow_dispatch

env:
  DAY_OF_WEEK: Lundi

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: Production 
    
    env:
      Greeting: Salut 

    steps:
      - name: "Étape 1 : Salutation (Variables classiques)"
        run: echo "$Greeting $First_Name. We are $DAY_OF_WEEK!"
        env:
          First_Name: Mona 

      - name: "Étape 2 : Utilisation sécurisée du Secret"
        env:
          # Le secret est injecté de manière invisible dans l'environnement de l'étape
          MON_SECRET_A_UTILISER: ${{ secrets.MON_SECRET_TEST }} 
        run: |
          echo "Le secret est actuellement utilisé en arrière-plan par le système."
          # Ici, au lieu d'un 'echo' pour l'afficher, on simule une action 
          # (par exemple, l'envoyer à un script Python ou s'authentifier)
          # IMPORTANT : On ne l'affiche JAMAIS avec un echo sur un dépôt public
